# Generated by Django 6.1.1 on 2026-09-11 11:11

import apps.exports.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('poem', 'Poem'), ('diwan', 'Diwan'), ('corpus', 'Corpus')], max_length=10)),
                ('format', models.CharField(choices=[('pdf', 'Pdf'), ('docx', 'Docx')], default='pdf', max_length=5)),
                ('file', models.FileField(max_length=255, upload_to=apps.exports.models.export_upload_to)),
                ('source_hash', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('diwan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='corpus.diwan')),
                ('poem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='corpus.poem')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('diwan__isnull', True), ('poem__isnull', False), ('scope', 'poem')), models.Q(('diwan__isnull', False), ('poem__isnull', True), ('scope', 'diwan')), models.Q(('diwan__isnull', True), ('poem__isnull', True), ('scope', 'corpus')), _connector='OR'), name='export_scope_matches_target'), models.UniqueConstraint(condition=models.Q(('scope', 'poem')), fields=('poem', 'format'), name='one_export_per_poem_format'), models.UniqueConstraint(condition=models.Q(('scope', 'diwan')), fields=('diwan', 'format'), name='one_export_per_diwan_format'), models.UniqueConstraint(condition=models.Q(('scope', 'corpus')), fields=('format',), name='one_export_per_corpus_format')],
            },
        ),
    ]
