# Generated by Django 6.1.1 on 2026-09-11 11:11

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='Diwan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('title_plain', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (red flags not resolved yet)'), ('review', 'In review'), ('published', 'Published')], default='draft', max_length=10)),
                ('corpus_abyat', models.PositiveIntegerField(default=0)),
                ('corpus_hemistichs', models.PositiveIntegerField(default=0)),
                ('corpus_words', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=12, unique=True)),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=500)),
                ('title_source', models.CharField(choices=[('name_line', 'Own name (line before the abyat)'), ('first_sadr', 'First sadr (no own name)')], default='first_sadr', max_length=10)),
                ('incipit', models.CharField(max_length=500)),
                ('title_plain', models.CharField(blank=True, max_length=500)),
                ('hemistichs_per_bayt', models.PositiveSmallIntegerField(default=2)),
                ('rhyme_letter', models.CharField(blank=True, max_length=4)),
                ('meter', models.CharField(blank=True, max_length=50)),
                ('bayt_count', models.PositiveIntegerField(default=0)),
                ('is_acrostic', models.BooleanField(default=False)),
                ('acrostic_match', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_open_flags', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft (red flags not resolved yet)'), ('review', 'In review'), ('published', 'Published')], default='draft', max_length=10)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diwan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poems', to='corpus.diwan')),
            ],
            options={
                'ordering': ['diwan__number', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('section', models.CharField(choices=[('muqaddima', 'Muqaddima (opening text)'), ('title', 'Name of the poem (right before the abyat)'), ('matn', 'Matn (the abyat)'), ('khatima', 'Khatima (after the abyat)')], max_length=10)),
                ('kind', models.CharField(choices=[('bayt', 'Bayt'), ('prose', 'Prose (basmala, salawat, dedication, closing formula...)'), ('title', 'Name of the poem'), ('header', 'Section header'), ('quran', "Qur'anic passage")], max_length=10)),
                ('bayt_number', models.PositiveIntegerField(blank=True, null=True)),
                ('hemistichs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField())),
                ('text_plain', models.TextField()),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='corpus.poem')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='LineTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('local', 'Local (as written in Senegal)')], default='local', max_length=10)),
                ('parts', django.contrib.postgres.fields.ArrayField(base_field=models.TextField())),
                ('is_manual', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='corpus.line')),
            ],
            options={
                'ordering': ['line__poem__diwan__number', 'line__poem__number', 'line__position'],
                'constraints': [models.UniqueConstraint(fields=('line', 'style'), name='one_transcription_per_line_and_style')],
            },
        ),
        migrations.AddIndex(
            model_name='poem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_plain'], name='poem_title_plain_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='poem',
            constraint=models.UniqueConstraint(fields=('diwan', 'number'), name='poem_number_unique_in_diwan'),
        ),
        migrations.AddConstraint(
            model_name='poem',
            constraint=models.UniqueConstraint(fields=('diwan', 'slug'), name='poem_slug_unique_in_diwan'),
        ),
        migrations.AddIndex(
            model_name='line',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_plain'], name='line_text_plain_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='line',
            constraint=models.UniqueConstraint(fields=('poem', 'position'), name='line_position_unique_in_poem'),
        ),
        migrations.AddConstraint(
            model_name='line',
            constraint=models.UniqueConstraint(fields=('poem', 'bayt_number'), name='line_bayt_number_unique_in_poem'),
        ),
        migrations.AddConstraint(
            model_name='line',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'title')), fields=('poem',), name='one_title_line_per_poem'),
        ),
        migrations.AddConstraint(
            model_name='line',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'title'), ('section', 'title')), models.Q(models.Q(('kind', 'title'), _negated=True), models.Q(('section', 'title'), _negated=True)), _connector='OR'), name='title_kind_matches_section'),
        ),
        migrations.AddConstraint(
            model_name='line',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bayt_number__isnull', False), ('hemistichs__len__in', [2, 4]), ('kind', 'bayt'), ('section', 'matn')), models.Q(models.Q(('kind', 'bayt'), _negated=True), ('bayt_number__isnull', True), ('hemistichs__len__gte', 1)), _connector='OR'), name='line_bayt_fields_consistent'),
        ),
    ]
