# Generated by Django 6.1.1 on 2026-09-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_title_source_bold'),
        ('corpus', '0002_unaccent'),
    ]

    operations = [
    ]
