# Generated by Django 6.1.1 on 2026-09-26 12:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_merge_0002_title_source_bold_0002_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='acrostic_spans',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list),
        ),
    ]
